### ISSUE TITLE
fix: mutable derived beacon 

### ISSUE THREAD

**Issue by yehorh** [jinyus/dart_beacon#105]
**Description**

Sometimes, it's necessary to aggregate multiple beacons from collections, for example, in mutable forms. When some of the beacons become unnecessary, they are disposed of, and the derived beacon stops working.

**Steps To Reproduce**
```dart
import 'dart:async';

import 'package:state_beacon_core/state_beacon_core.dart';

Future<void> main() async {
  // BeaconObserver.instance = LoggingObserver();

  final beacons = Beacon.list(<ReadableBeacon<bool>>[]);
  late final derivedBeacon = Beacon.derived(() {
    final list = beacons.value;
    return list.every((beacon) => beacon.value);
  }, name: 'derivedBeacon');
  derivedBeacon.subscribe((value) {
    print('derivedBeacon: $value');
  });
  await Future<void>.delayed(Duration.zero);

  beacons.add(Beacon.writable(true));
  await Future<void>.delayed(Duration.zero);
  beacons.add(Beacon.writable(false));
  await Future<void>.delayed(Duration.zero);
  beacons.value.last.dispose();
  beacons.remove(beacons.value.last);
  await Future<void>.delayed(Duration.zero);
  beacons.add(Beacon.writable(true));
  await Future<void>.delayed(Duration.zero);
}
```

output:
```
derivedBeacon: true
derivedBeacon: false

Exited.
```

**Comment by jinyus** [comment]
This was done prevent misuse and memory leaks. The idea of disposal is to make the object garbage collectible. The object will not be garbage collected if it still has references. 

So if a derived beacon still has a reference to a beacon, disposing the beacon doesn't make much sense since it will live in memory until the derived beacon itself is GC'ed.

The general rule is: a derived beacon/effect will be disposed when any of its sources are disposed.

A beacon/signal is just a value and a list of listeners, all disposing does is empty the list of listeners so if the list if already empty, disposing doesn't gain much. I use `dispose` as a declaration that the beacon will never be used again (read/written) and is ready to be garbage collected.

In your scenario, the beacon will be properly GC'ed when removed from the `ListBeacon` because it will no longer be referenced by the `DerivedBeacon`, so there's no need to call `dispose()`. `beacons.remove(beacons.value.last);` is enough to prevent memory leaks.

**Comment by yehorh** [comment]
Thanks, I understood that. Now, I should review my approach to disposing of more complex objects in Beacons and keep in mind when something must be disposed of.

I have added a logger and seen that.
